[book]
authors = ["Tavian Barnes"]
title = "tavianator.com"

[build]
build-dir = "site"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["custom.css"]
additional-js = ["katex.js"]
git-repository-url = "https://github.com/tavianator/tavianator.com"
